name: kickluck_mvp
description: KickLuck MVP milestone 7 - production polish and Android internal-test configuration.
publish_to: "none"

version: 0.9.0+9

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  share_plus: ^10.1.4
  path_provider: ^2.1.4
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/kickluck_app_icon_1024.png
  min_sdk_android: 23
  adaptive_icon_background: "#07100C"
  adaptive_icon_foreground: assets/branding/kickluck_app_icon_1024.png

flutter_native_splash:
  color: "#07100C"
  image: assets/branding/kickluck_app_icon_1024.png
  android: true
  ios: false
  android_12:
    color: "#07100C"
    image: assets/branding/kickluck_app_icon_1024.png
